### ISSUE TITLE
Handling PertinentNegativeNull

### ISSUE THREAD

**Issue by jmnarloch** [ragnor/simple-spring-memcached#55]
I've doubts related to the way how the PertinentNegativeNull case is being handled in https://github.com/ragnor/simple-spring-memcached/blob/master/spring-cache/src/main/java/com/google/code/ssm/spring/SSMCache.java#L107

Correct me if I am wrong but what I understand is that PertinentNegativeNull indicates that there is no value in the cache, right? The only problem is what is going on next, the null value is being wrapped with SimpleValueWrapper which Spring Cache is going to treat as cache hit. I'm observing an odd behaviour that despite the value not being cached, the advice method by the Spring Cache is not being invoked and a null is being returned from the cache. I am using Spring 4.2 and it's calling the SSMCache#get(Object) method.

I think that in case of PertinentNegativeNull the null shouldn't be wrapped into SimpleValueWrapper, but a null reference should be returned indicating a cache miss. What do you think?

**Comment by ragnor** [comment]
_PertinentNegativeNull_ is for marking that value is null (Java null), it isn't for a cache miss. If there is a cache miss then a null will be returned by SSM (not _PertinentNegativeNull_) and nothing will be stored in memcached. Without _PertinentNegativeNull_ it won't be possible to distinct if there is no value or a null was set (Java 'null') because memcached clients treat them the same. So set('someKey', null) is the same as del('someKey') and in both cases get('someKey') will return null (cache miss).

**Comment by jmnarloch** [comment]
Ok, thanks for explanation, got necessary confused but that. Thanks!
