### ISSUE TITLE
SSMCache put is swallowing all the exceptions

### ISSUE THREAD

**Issue by ek-ex** [ragnor/simple-spring-memcached#65]
If there is an exception of any sort, the method is swallowing it and only logging. This is very bad since the client will not know when a call failed and would need to be retried.

https://github.com/ragnor/simple-spring-memcached/blob/master/spring-cache/src/main/java/com/google/code/ssm/spring/SSMCache.java#L168

Was there any reason why it was done this way ?

**Comment by ragnor** [comment]
It works in such way because caching layer should be transparent to rest of application. This is a main idea behind SSM. The app should work in the same way with disabled or enabled cache. 

I've checked other implementations of _org.springframework.cache.Cache_ and it seams that their don't mute exceptions but return them to client (caller).

What do you think? How it should work? Is it specified in Spring Cache?

**Comment by RichardBradley** [comment]
We have a problem where a thread interrupt is being swallowed by SSMCache, which then simulates a cache miss and allows the AOP wrapped method to proceed. 

I understand the rationale for swallowing cache errors, but it seems that InterruptedException should be allowed to propagate.

**Comment by RichardBradley** [comment]
> What do you think? How it should work? Is it specified in Spring Cache?

In standard Spring caching, the exception handling behaviour is configurable: https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html#cache-annotation-driven-settings

**Comment by kinpa0a** [comment]
@ragnor 

Hello.
Do you have any plan to modify SSM to register custom exception handler?

**Comment by ragnor** [comment]
I'd like to add it to SSM but currently I'm lack of time. I don't know when
I find a time to implement it.
Do you consider creating a pull request?

**Comment by ragnor** [comment]
A new settings in SSMCache _muteExceptions_ allows to control if an exception should be muted or not. The default is true so it works as currently/
