### ISSUE TITLE
Cached data storage in application memory when using the annotations

### ISSUE THREAD

**Issue by ganapathi004** [ragnor/simple-spring-memcached#86]
Hi @ragnor 

This issue is purely a question, may be even a dumb one. My question is, when we annotate a method with any of the available annotations for the data to be cached, will this store the output of that method in application memory or will this just check the cache is available in memcached and return it?

Like 
```
@ReadThroughAssignCache(namespace = "test", assignedKey="testData")
public List<String> doSomething(){
    return list;
}
```
roughly translates to 

```
if(memcahcedClient.get(testData) != null) 
    return memcahcedClient.get(testData);
else
    ...proceed to fetch the data from source (method gets executed)
```

Thank You.

**Comment by ragnor** [comment]
Hi,

SSM doesn't cache anything in local/application memory. The main cache storage is memcached. 
In case of @ReadThroughAssignCache the flow is:

1. interrupt call of annotated method
1. compute cache key (use defined assignedKey)
1. get data from cache using cache key, if there are data under given cache key go to last (6) step, otherwise proceed next step
1. execute method's body
1. store result of method in cache under cache key
1. return result to caller

So you shouldn't use if-else but just wrap "...proceed to fetch the data from source (method gets executed)" with a method and annotate it with proper annotation. SSM will take care of rest. 
Hope now it's clear for you.

BTW. Just remember that in Spring self-invocation (using this.myMethod()) are not intercepted so caching won't work.

**Comment by ganapathi004** [comment]
Great. Thanks for the explanation. And many thanks for maintaining this.
